apiVersion: v1
kind: Service
metadata:
  name: sample-service
spec:
  type: ClusterIP
  selector:
    app: sample-service
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: sample-http