apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: ClusterIP
  selector:
    app: my-service
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: my-http